# Generated by Django 5.1.15 on 2026-09-03 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_feature_labels_seed'),
        ('tenants', '0004_rls_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('device_offline', 'Urządzenie offline'), ('value_out_of_range', 'Wartość poza zakresem'), ('device_message', 'Komunikat urządzenia'), ('provider_account', 'Konto producenta'), ('verify_mismatch', 'Komenda niepotwierdzona'), ('worker_down', 'Brak workera')])),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('device_offline', 'Urządzenie offline'), ('value_out_of_range', 'Wartość poza zakresem'), ('device_message', 'Komunikat urządzenia'), ('provider_account', 'Konto producenta'), ('verify_mismatch', 'Komenda niepotwierdzona'), ('worker_down', 'Brak workera')])),
                ('severity', models.TextField(choices=[('info', 'informacja'), ('warning', 'ostrzeżenie'), ('critical', 'krytyczny')], default='warning')),
                ('key', models.TextField(default='')),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tenants.tenant')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['tenant', 'closed_at', '-opened_at'], name='alerts_tenant_open'), models.Index(fields=['device', 'type', 'key'], name='alerts_dedup')],
            },
        ),
    ]
