# Generated by Django 5.1.15 on 2026-09-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.TextField(choices=[('device_offline', 'Urządzenie offline'), ('value_out_of_range', 'Wartość poza zakresem'), ('device_message', 'Komunikat urządzenia'), ('provider_account', 'Konto producenta'), ('verify_mismatch', 'Komenda niepotwierdzona'), ('worker_down', 'Brak workera'), ('backup_failed', 'Backup nieudany')]),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='type',
            field=models.TextField(choices=[('device_offline', 'Urządzenie offline'), ('value_out_of_range', 'Wartość poza zakresem'), ('device_message', 'Komunikat urządzenia'), ('provider_account', 'Konto producenta'), ('verify_mismatch', 'Komenda niepotwierdzona'), ('worker_down', 'Brak workera'), ('backup_failed', 'Backup nieudany')]),
        ),
    ]
