# Generated by Django 5.1.15 on 2026-09-02 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_rls_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.TextField(primary_key=True, serialize=False)),
                ('hostname', models.TextField(blank=True, default='')),
                ('concurrency', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_beat_at', models.DateTimeField()),
                ('jobs_done', models.BigIntegerField(default=0)),
                ('jobs_failed', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'worker_heartbeats',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider_account_id', models.UUIDField(blank=True, null=True)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('priority', models.IntegerField(default=100)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('queued', 'W kolejce'), ('running', 'W toku'), ('done', 'Zakończone'), ('failed', 'Nieudane')], default='queued')),
                ('last_error', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['status', 'run_at', 'priority'], name='jobs_status_run_at_prio')],
            },
        ),
    ]
