# Generated by Django 5.1.15 on 2026-09-04 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_timescaledb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.TextField(blank=True, default='')),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.TextField(blank=True, default='')),
                ('password_enc', models.BinaryField(blank=True, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.TextField(blank=True, default='')),
                ('timeout_s', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'mail_settings',
            },
        ),
    ]
