# Generated by Django 5.1.15 on 2026-09-03 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_feature_labels_seed'),
        ('tenants', '0004_rls_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acted_as_operator', models.BooleanField(default=False)),
                ('feature_name', models.TextField()),
                ('command_name', models.TextField()),
                ('params', models.JSONField(default=dict)),
                ('value_before', models.JSONField(blank=True, null=True)),
                ('value_after', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(choices=[('draft', 'Szkic'), ('confirmed', 'Potwierdzona'), ('executing', 'Wykonywana'), ('succeeded', 'Wysłana'), ('failed', 'Nieudana'), ('verify_pending', 'Oczekuje na weryfikację'), ('verified', 'Zweryfikowana'), ('verify_mismatch', 'Niezgodna z odczytem'), ('rejected', 'Odrzucona'), ('expired', 'Wygasła')], default='draft')),
                ('sensitive', models.BooleanField(default=False)),
                ('reauth_verified', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('api_status', models.IntegerField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('verify_attempts', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='commands_device_created'), models.Index(fields=['tenant', '-created_at'], name='commands_tenant_created')],
            },
        ),
    ]
