# Generated by Django 5.1.15 on 2026-09-02 22:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_rls_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('state', models.TextField(primary_key=True, serialize=False)),
                ('code_verifier', models.TextField()),
                ('provider', models.TextField()),
                ('redirect_uri', models.TextField()),
                ('label', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_states',
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.TextField()),
                ('external_user_id', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, default='')),
                ('refresh_token_enc', models.BinaryField()),
                ('access_token_enc', models.BinaryField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('status', models.TextField(choices=[('active', 'Aktywne'), ('reauth_required', 'Wymaga ponownej autoryzacji'), ('rate_limited', 'Limit API wyczerpany'), ('disabled', 'Wyłączone')], default='active')),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('status_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_until', models.DateTimeField(blank=True, null=True)),
                ('budget_limit', models.IntegerField(default=1450)),
                ('budget_window_s', models.IntegerField(default=86400)),
                ('budget_reserve_pct', models.IntegerField(default=15)),
                ('short_limit', models.IntegerField(default=120)),
                ('short_window_s', models.IntegerField(default=600)),
                ('budget_overcommitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'provider_accounts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.TextField(choices=[('poll', 'poll'), ('command', 'command'), ('verify', 'verify'), ('refresh', 'refresh'), ('discover', 'discover'), ('refresh_token', 'refresh_token')])),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_type', models.TextField(blank=True, null=True)),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='providers.provideraccount')),
            ],
            options={
                'db_table': 'api_calls',
                'indexes': [models.Index(fields=['provider_account', '-ts'], name='api_calls_account_ts'), models.Index(fields=['ts'], name='api_calls_ts')],
            },
        ),
    ]
