# Generated by Django 5.1.15 on 2026-09-02 19:49

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField(choices=[('superadmin', 'Superadmin'), ('technician', 'Serwisant'), ('tenant_admin', 'Administrator klienta'), ('tenant_user', 'Użytkownik klienta')])),
                ('token_hash', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField(choices=[('superadmin', 'Superadmin'), ('technician', 'Serwisant'), ('tenant_admin', 'Administrator klienta'), ('tenant_user', 'Użytkownik klienta')])),
                ('totp_secret_enc', models.BinaryField(blank=True, null=True)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('backup_codes_hash', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('ui_theme', models.TextField(choices=[('light', 'Jasny'), ('dark', 'Ciemny')], default='light')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
