# Generated by Django 5.1.15 on 2026-09-02 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_lower', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'login_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.TextField(unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitations_role_tenant_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='users_role_tenant_consistency',
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['superadmin', 'technician']), ('tenant__isnull', True)), models.Q(('role__in', ['tenant_admin', 'tenant_user']), ('tenant__isnull', False)), _connector='OR'), name='invitations_role_tenant_consistency'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['superadmin', 'technician']), ('tenant__isnull', True)), models.Q(('role__in', ['tenant_admin', 'tenant_user']), ('tenant__isnull', False)), _connector='OR'), name='users_role_tenant_consistency'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email_lower', 'ts'], name='login_attempts_email_ts'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip', 'ts'], name='login_attempts_ip_ts'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
