# Generated by Django 5.1.15 on 2026-09-02 22:36

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_rls'),
        ('tenants', '0004_rls_user_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('feature_name', models.TextField()),
                ('property_name', models.TextField()),
                ('ts_polled', models.DateTimeField(primary_key=True, serialize=False)),
                ('ts_device', models.DateTimeField(blank=True, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feature_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.TextField()),
                ('external_ids', models.JSONField()),
                ('model', models.TextField(blank=True, default='')),
                ('serial', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('mode', models.TextField(choices=[('read', 'Odczyt'), ('control', 'Sterowanie')], default='read')),
                ('poll_interval_s', models.IntegerField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(choices=[('unknown', 'Nieznany'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Błąd'), ('rate_limited', 'Limit API')], default='unknown')),
                ('status_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_detail', models.TextField(blank=True, null=True)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('commands_per_hour_limit', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='providers.provideraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('unknown', 'Nieznany'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Błąd'), ('rate_limited', 'Limit API')])),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'device_status_history',
            },
        ),
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('installation_id', models.TextField()),
                ('gateway_serial', models.TextField()),
                ('device_id', models.TextField()),
                ('model', models.TextField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, null=True)),
                ('online', models.BooleanField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_devices', to='providers.provideraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'discovered_devices',
            },
        ),
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_ready', models.BooleanField(default=True)),
                ('group_key', models.TextField()),
                ('properties_schema', models.JSONField(default=dict)),
                ('commands_schema', models.JSONField(default=dict)),
                ('command_uris', models.JSONField(default=dict)),
                ('unsupported_commands', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_definitions', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'feature_definitions',
            },
        ),
        migrations.CreateModel(
            name='FeatureJsonHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_name', models.TextField()),
                ('property_name', models.TextField()),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value_json', models.JSONField()),
                ('value_hash', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'feature_json_history',
            },
        ),
        migrations.CreateModel(
            name='FeatureLatest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_name', models.TextField()),
                ('property_name', models.TextField()),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('ts_device', models.DateTimeField(blank=True, null=True)),
                ('ts_polled', models.DateTimeField()),
                ('last_history_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_values', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'feature_latest',
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(models.F('provider_account'), models.F('external_ids__installationId'), models.F('external_ids__gatewaySerial'), models.F('external_ids__deviceId'), name='devices_external_ids_unique'),
        ),
        migrations.AddIndex(
            model_name='devicestatushistory',
            index=models.Index(fields=['device', '-since'], name='device_status_hist_dev'),
        ),
        migrations.AddConstraint(
            model_name='discovereddevice',
            constraint=models.UniqueConstraint(fields=('provider_account', 'installation_id', 'gateway_serial', 'device_id'), name='discovered_devices_pk'),
        ),
        migrations.AddConstraint(
            model_name='featuredefinition',
            constraint=models.UniqueConstraint(fields=('device', 'feature_name'), name='feature_definitions_uq'),
        ),
        migrations.AddConstraint(
            model_name='featurelatest',
            constraint=models.UniqueConstraint(fields=('device', 'feature_name', 'property_name'), name='feature_latest_pk'),
        ),
    ]
