# Generated by Django 5.1.15 on 2026-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_timescale_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLabel',
            fields=[
                ('feature_name_pattern', models.TextField(primary_key=True, serialize=False)),
                ('label_pl', models.TextField(blank=True, default='')),
                ('description_pl', models.TextField(blank=True, default='')),
                ('group_key', models.TextField(blank=True, null=True)),
                ('sort', models.IntegerField(default=100)),
                ('highlight', models.BooleanField(default=False)),
                ('report_default', models.BooleanField(default=False)),
                ('command_property_map', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_labels',
                'ordering': ['feature_name_pattern'],
            },
        ),
        migrations.AlterModelTable(
            name='featurevalue',
            table='feature_values_rls',
        ),
    ]
