# Generated by Django 5.1.15 on 2026-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_feature_labels_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hidden_widgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
