# Generated by Django 5.1.15 on 2026-09-03 11:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_rls_user_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('report_type', models.TextField(choices=[('operation', 'Praca urządzenia'), ('energy', 'Energia'), ('availability', 'Dostępność'), ('changes', 'Zmiany')])),
                ('device_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('period', models.TextField(choices=[('last_day', 'poprzedni dzień'), ('last_week', 'poprzedni tydzień'), ('last_month', 'poprzedni miesiąc')], default='last_month')),
                ('resolution', models.TextField(default='auto')),
                ('format', models.TextField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf')),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('cron', models.TextField(default='0 6 1 * *')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.TextField(choices=[('operation', 'Praca urządzenia'), ('energy', 'Energia'), ('availability', 'Dostępność'), ('changes', 'Zmiany')])),
                ('params', models.JSONField(default=dict)),
                ('format', models.TextField(choices=[('pdf', 'PDF'), ('csv', 'CSV')])),
                ('status', models.TextField(choices=[('pending', 'w przygotowaniu'), ('done', 'gotowy'), ('failed', 'błąd')], default='pending')),
                ('error', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='tenants.tenant')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='reports.reportschedule')),
            ],
            options={
                'db_table': 'report_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
